name: 'Match Comment Phrase'
description: 'github action to match a phrase within a github comment and outputs a boolean value when found by a specific mode'
author: 'Layton Whiteley'
branding:
  icon: 'bell'
  color: 'purple'
inputs:
  phrase:
    required: true
    description: 'the phrase to look for in the issue comment'
  mode:
    description: 'the mode is how the action checks for the phrase within the comment. possible values: starts_line | starts_comment | within'
    default: 'starts_line'
  include_code:
    description: 'boolean to determine if the action should also search in code snippets'
    default: 'false'
  own_line:
    description: 'boolean to determine if phrase is only matched if it occupies its own line. Applicable modes: "starts_line", "starts_comment"  '
    default: 'false'
  reactions:
    description: 'Comma separated list of valid reactions to add to the comment if phrase is found'
    default: ''
  token:
    description: 'The github token of the run. This can also be provided as an environment variable'
    default: ''
outputs:
  match_found:
    description: 'Boolean string depending on if the phrase was found. Possible values: true or false'
  comment_body:
    description: 'The comment body'
  comment_line:
    description: 'The comment line where the first valid match of the phrase is found'
  issue_number:
    description: 'the associated issue or pull request number'
  sha:
    description: 'the associated head sha of pull request'
  issue_creator:
    description: 'the creator of the issue'
  issue_actor:
    description: 'the user that commented. Defaults to issue creator if not found'
runs:
  using: 'node20'
  main: 'dist/index.js'
